// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.poc.domain;

import com.rahul.poc.domain.Gender;

privileged aspect Gender_Roo_JavaBean {
    
    public String Gender.getGender() {
        return this.gender;
    }
    
    public void Gender.setGender(String gender) {
        this.gender = gender;
    }
    
    public String Gender.getGenderAlias() {
        return this.genderAlias;
    }
    
    public void Gender.setGenderAlias(String genderAlias) {
        this.genderAlias = genderAlias;
    }
    
}
