// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.poc.domain;

import com.rahul.poc.domain.Person;
import java.math.BigInteger;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Persistent;

privileged aspect Person_Roo_Mongo_Entity {
    
    declare @type: Person: @Persistent;
    
    @Id
    private BigInteger Person.id;
    
    public BigInteger Person.getId() {
        return this.id;
    }
    
    public void Person.setId(BigInteger id) {
        this.id = id;
    }
    
}
