// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.poc.domain;

import com.rahul.poc.domain.Gender;
import com.rahul.poc.domain.Person;

privileged aspect Person_Roo_JavaBean {
    
    public String Person.getFName() {
        return this.fName;
    }
    
    public void Person.setFName(String fName) {
        this.fName = fName;
    }
    
    public String Person.getLName() {
        return this.lName;
    }
    
    public void Person.setLName(String lName) {
        this.lName = lName;
    }
    
    public Gender Person.getGender() {
        return this.gender;
    }
    
    public void Person.setGender(Gender gender) {
        this.gender = gender;
    }
    
}
