// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.poc.domain;

import com.rahul.poc.domain.Gender;
import com.rahul.poc.domain.GenderDataOnDemand;
import com.rahul.poc.service.GenderService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect GenderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GenderDataOnDemand: @Component;
    
    private Random GenderDataOnDemand.rnd = new SecureRandom();
    
    private List<Gender> GenderDataOnDemand.data;
    
    @Autowired
    GenderService GenderDataOnDemand.genderService;
    
    public Gender GenderDataOnDemand.getNewTransientGender(int index) {
        Gender obj = new Gender();
        setGender(obj, index);
        setGenderAlias(obj, index);
        return obj;
    }
    
    public void GenderDataOnDemand.setGender(Gender obj, int index) {
        String gender = "gender_" + index;
        obj.setGender(gender);
    }
    
    public void GenderDataOnDemand.setGenderAlias(Gender obj, int index) {
        String genderAlias = "genderAlias_" + index;
        obj.setGenderAlias(genderAlias);
    }
    
    public Gender GenderDataOnDemand.getSpecificGender(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Gender obj = data.get(index);
        BigInteger id = obj.getId();
        return genderService.findGender(id);
    }
    
    public Gender GenderDataOnDemand.getRandomGender() {
        init();
        Gender obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return genderService.findGender(id);
    }
    
    public boolean GenderDataOnDemand.modifyGender(Gender obj) {
        return false;
    }
    
    public void GenderDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = genderService.findGenderEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Gender' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Gender>();
        for (int i = 0; i < 10; i++) {
            Gender obj = getNewTransientGender(i);
            try {
                genderService.saveGender(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
