// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.poc.repository;

import com.rahul.poc.domain.Person;
import com.rahul.poc.repository.PersonRepository;
import java.math.BigInteger;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Repository;

privileged aspect PersonRepository_Roo_Mongo_Repository {
    
    declare parents: PersonRepository extends PagingAndSortingRepository<Person, BigInteger>;
    
    declare @type: PersonRepository: @Repository;
    
}
