// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.poc.controller;

import com.rahul.poc.controller.GenderController;
import com.rahul.poc.domain.Gender;
import com.rahul.poc.service.GenderService;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect GenderController_Roo_Controller {
    
    @Autowired
    GenderService GenderController.genderService;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String GenderController.create(@Valid Gender gender, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, gender);
            return "genders/create";
        }
        uiModel.asMap().clear();
        genderService.saveGender(gender);
        return "redirect:/genders/" + encodeUrlPathSegment(gender.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String GenderController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Gender());
        return "genders/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String GenderController.show(@PathVariable("id") BigInteger id, Model uiModel) {
        uiModel.addAttribute("gender", genderService.findGender(id));
        uiModel.addAttribute("itemId", id);
        return "genders/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String GenderController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("genders", genderService.findGenderEntries(firstResult, sizeNo));
            float nrOfPages = (float) genderService.countAllGenders() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("genders", genderService.findAllGenders());
        }
        return "genders/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String GenderController.update(@Valid Gender gender, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, gender);
            return "genders/update";
        }
        uiModel.asMap().clear();
        genderService.updateGender(gender);
        return "redirect:/genders/" + encodeUrlPathSegment(gender.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String GenderController.updateForm(@PathVariable("id") BigInteger id, Model uiModel) {
        populateEditForm(uiModel, genderService.findGender(id));
        return "genders/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String GenderController.delete(@PathVariable("id") BigInteger id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Gender gender = genderService.findGender(id);
        genderService.deleteGender(gender);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/genders";
    }
    
    void GenderController.populateEditForm(Model uiModel, Gender gender) {
        uiModel.addAttribute("gender", gender);
    }
    
    String GenderController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
