// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rahul.poc.service;

import com.rahul.poc.service.GenderServiceImpl;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GenderServiceImpl_Roo_Service {
    
    declare @type: GenderServiceImpl: @Service;
    
    declare @type: GenderServiceImpl: @Transactional;
    
}
